create table if not exists instrument_meta (
  symbol text primary key,
  exchange text,
  yahoo_symbol text,
  quote_type text,
  asset_type text,
  is_etf boolean,
  is_mutual_fund boolean,
  is_closed_end_fund boolean,
  is_trust boolean,
  is_index boolean,
  category text,
  fund_family text,
  legal_type text,
  currency text,
  underlying_symbol text,
  nav_price numeric,
  expense_ratio numeric,
  total_assets numeric,
  yield numeric,
  ytd_return numeric,
  three_year_avg_return numeric,
  five_year_avg_return numeric,
  beta_3y numeric,
  long_name text,
  attributes jsonb,
  updated_at timestamp default now()
);
